### ISSUE TITLE
Error: Cannot parse file: Unexpected token  in JSON at position 289.

### ISSUE THREAD

**Issue by brucefroggert2** [misode/upgrader#10]
An error occurred while loading a data pack.
Data Pack: 

```
Error: Cannot parse file: Unexpected token 
 in JSON at position 289.
    at t (src/Pack.ts:106:9)
    at (https://misode.github.io/upgrader/assets/index.0926d573.js:1:41779) (src/Pack.ts:90:26)
    at async Promise.all (index 755)
    at category (src/Pack.ts:77:13)
    at async Promise.all (index 3)
    at (https://misode.github.io/upgrader/assets/index.0926d573.js:1:41536) (src/Pack.ts:73:32)
    at async Promise.all (index 0)
    at promise (src/App.tsx:69:57)
    at async Promise.all (index 0)
    at newPacks (src/App.tsx:69:9)
```

**Comment by misode** [comment]
Could you upload the datapack that you're trying to upgrade?

**Comment by brucefroggert2** [comment]
https://www.planetminecraft.com/data-pack/orium-1-0-advanced-resource-processing-and-item-enchanting/

**Comment by brucefroggert2** [comment]
Sorry for late reaction I didn't had time to respond

**Comment by misode** [comment]
The datapack contains invalid JSON in at least `data/orium/loot_tables/divine_guidebook.json`. More specifically, strings can't span multiple lines.

I'll workaround this by accepting a pack with JSON errors, but ignoring those files and showing a warning.

![image](https://user-images.githubusercontent.com/17352009/144736462-255218a1-a935-4bae-a5be-901472c6b270.png)

**Comment by misode** [comment]
You now get a warning, but the rest of the pack gets upgraded.
![image](https://user-images.githubusercontent.com/17352009/144736876-c408ea7c-61f0-41aa-b8de-2c75e3be0597.png)

**Comment by brucefroggert2** [comment]
thnx for the help really fast help
