### ISSUE TITLE
Upgrades without errors but doesn't work in minecraft

### ISSUE THREAD

**Issue by mooziii** [misode/upgrader#12]
Hi, i upgraded my datapack to 1.18 but when i load it, i get this error:

```[14:45:21] [Render thread/WARN]: Failed to validate datapack
java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Error loading registry data: Missing referenced custom/removed registry entry for registry ResourceKey[minecraft:root / minecraft:worldgen/placed_feature] named minecraft:ore_iron
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) [?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) [?:?]
	at auh.c(BlockableEventLoop.java:193) [auh.class:?]
	at aul.c(SourceFile:23) [aul.class:?]
	at auh.y(BlockableEventLoop.java:158) [auh.class:?]
	at auh.bp(BlockableEventLoop.java:135) [auh.class:?]
	at dxo.f(SourceFile:1080) [dxo.class:?]
	at dxo.e(SourceFile:733) [dxo.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:238) [Main.class:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.3.jar:2.3]
Caused by: com.google.gson.JsonParseException: Error loading registry data: Missing referenced custom/removed registry entry for registry ResourceKey[minecraft:root / minecraft:worldgen/placed_feature] named minecraft:ore_iron
	at gy.a(SourceFile:219) ~[gy.class:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at gy.a(SourceFile:219) ~[gy.class:?]
	at gy.a(SourceFile:210) ~[gy.class:?]
	at yd.a(SourceFile:37) ~[yd.class:?]
	at yd.a(SourceFile:31) ~[yd.class:?]
	at egm.a(SourceFile:319) ~[egm.class:?]
	at egh.a(SourceFile:458) ~[egh.class:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 14 more```

**Comment by mooziii** [comment]
+ when i upgrade my 1.16.5 pack to 1.17 i get this

```[14:53:06] [Render thread/WARN]: Failed to validate datapack
java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Error loading registry data: Missing value [3] : ResourceKey[minecraft:worldgen/configured_feature / minecraft:spruce_snowy]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) [?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
	at aqu.c(SourceFile:151) [1.17.jar:?]
	at aqy.c(SourceFile:23) [1.17.jar:?]
	at aqu.z(SourceFile:125) [1.17.jar:?]
	at aqu.bq(SourceFile:110) [1.17.jar:?]
	at dvo.f(SourceFile:1077) [1.17.jar:?]
	at dvo.e(SourceFile:730) [1.17.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:217) [1.17.jar:?]
Caused by: com.google.gson.JsonParseException: Error loading registry data: Missing value [3] : ResourceKey[minecraft:worldgen/configured_feature / minecraft:spruce_snowy]
	at gx.a(SourceFile:221) ~[1.17.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at gx.a(SourceFile:221) ~[1.17.jar:?]
	at gx.a(SourceFile:212) ~[1.17.jar:?]
	at wt.a(SourceFile:57) ~[1.17.jar:?]
	at wt.a(SourceFile:51) ~[1.17.jar:?]
	at eei.a(SourceFile:319) ~[1.17.jar:?]
	at eed.a(SourceFile:459) ~[1.17.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	... 8 more
```

**Comment by misode** [comment]
Hey, can you attach the data pack before you upgrading it?

**Comment by mooziii** [comment]
[1.16.5 original.zip](https://github.com/misode/upgrader/files/8010662/1.16.5.original.zip)

**Comment by misode** [comment]
Okay I see what the issue is. It's basically #5, but I should probably try to fix that.

**Comment by misode** [comment]
Your first error (the one with `iron_ore`) is because they split iron ore into 3 placed features. And when you use it in the `ore_iron_double` configured feature, there's not really a good way to automatically fix that.

**Comment by mooziii** [comment]
1.17.1 works now after removing `spruce_snowy`, i`ll try fixxing 1.18 later
