### ISSUE TITLE
Error: Cannot upgrade pack with status 'done'.

### ISSUE THREAD

**Issue by louanfontenele** [misode/upgrader#13]
An error occurred while upgrading a data pack.
Data Pack: [the-forbidden-castle-v1-1.zip](https://github.com/misode/upgrader/files/8224569/the-forbidden-castle-v1-1.zip)
```
Error: Cannot upgrade pack with status 'done'.
    at Object.h (src/Pack.ts:182:9)
    at (https://misode.github.io/upgrader/assets/index.420fd402.js:6:1143) (src/components/PackCard.tsx:60:15)
    at Object.__ (src/components/PackCard.tsx:67:13)
    at Me (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/vendor.65c42646.js:1:9786) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at zr (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

Please, i need upgrade this datapack to 1.18.2 please someone help me

**Comment by misode** [comment]
I managed to reproduce this using the following steps:
1. Drop a data pack and it it fully upgrade
2. Drop a second data pack
3. While it's upgrading or zipping, remove the first data pack with the X
4. When the second data pack finishes, the error shows and upgrading the second data pack fails.
