### ISSUE TITLE
Error: The dropped files contain no zip files. Please zip the data pack first.

### ISSUE THREAD

**Issue by Cop4Terminator** [misode/upgrader#14]
An error occurred while loading a data pack.
Data Pack: 

```
Error: The dropped files contain no zip files. Please zip the data pack first.
    at Object.l (src/App.tsx:67:23)
    at HTMLElement.Ye (../../node_modules/preact/dist/preact.module.js:1:4351)
```

**Comment by misode** [comment]
Make sure that you're not dropping a folder, but instead zip the folder first and then upload it to the site.
