### ISSUE TITLE
TypeError: Error fixing biome minecraft:nether_wastes: i.forEach is not a function

### ISSUE THREAD

**Issue by u3ux** [misode/upgrader#22]
An error occurred while upgrading a data pack.
Data Pack:
[FlatWorld+ 1.0.1.zip](https://github.com/misode/upgrader/files/8840837/FlatWorld%2B.1.0.1.zip)
Was gonna update my pack to 1.19 but I guess not right now

```
TypeError: Error fixing biome minecraft:nether_wastes: i.forEach is not a function
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:41136) (src/fixes/1.19/Carver.ts:7:21)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4264) (src/Fix.ts:30:11)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4097) (src/Fix.ts:13:10)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4091) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4711) (src/Fix.ts:63:18)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4091) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4555) (src/Fix.ts:50:39)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4091) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4902) (src/Fix.ts:79:58)
    at (https://misode.github.io/upgrader/assets/index.931b7c1a.js:1:4091) (src/Fix.ts:12:21)
```

**Comment by misode** [comment]
I fixed this specific problem, but while testing your data pack I discovered at least one other issue, working on that now

**Comment by misode** [comment]
@u3ux After c2f8a7c17660508405bb23785b85f2d8c9d61780 your pack is able to validate in 1.19. Let me know if there are still problems with it.
