### ISSUE TITLE
TypeError: Error fixing structure set fokastudio:end/islands: Cannot read properties of undefined (reading 'structure')

### ISSUE THREAD

**Issue by zopn333** [misode/upgrader#25]
An error occurred while upgrading a data pack.
Data Pack: fokastudio-s-ender-expansion-v1-4a-e840

```
TypeError: Error fixing structure set fokastudio:end/islands: Cannot read properties of undefined (reading 'structure')
    at Ui (src/fixes/1.19/Structure.ts:94:69)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:77708) (src/fixes/1.19/Structure.ts:7:63)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:870) (src/Fix.ts:30:11)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:701) (src/Fix.ts:13:10)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:695) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:1319) (src/Fix.ts:63:21)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:695) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:1163) (src/Fix.ts:51:7)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:695) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.c602c2e0.js:15:1511) (src/Fix.ts:79:60)
```

**Comment by misode** [comment]
@zopn333 Could you upload your data pack please?

**Comment by zopn333** [comment]
[fokastudio-s-ender-expansion-v1-4a-e840.zip](https://github.com/misode/upgrader/files/8931856/fokastudio-s-ender-expansion-v1-4a-e840.zip)

**Comment by misode** [comment]
Found and fixed the issue. However keep in mind that since you commented out the structures in `fokastudio:end/islands`, the comments will be removed and not upgraded.
