### ISSUE TITLE
Error: Found pack format 3, which does not match version 1.16.5

### ISSUE THREAD

**Issue by rafciu41** [misode/upgrader#28]
An error occurred while upgrading a data pack.
Data Pack: 

```
Error: Found pack format 3, which does not match version 1.16.5
    at Object.b (src/Pack.ts:218:10)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:20:1688) (src/components/PackCard.tsx:68:15)
    at Object.__ (src/components/PackCard.tsx:75:37)
    at Tt (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:1:10951) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at yn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

**Comment by misode** [comment]
The error is exactly as it says, you have 1.16.5 selected but your pack format is 3, which is not a valid pack format. If you're sure that your data pack works in 1.16.5, you can change your original pack format to 6
