### ISSUE TITLE
Error: Invalid version range: 1.19 > 1.17.1

### ISSUE THREAD

**Issue by UlianovKazah** [misode/upgrader#29]
An error occurred while upgrading a data pack.
Data Pack: 

```
Error: Invalid version range: 1.19 > 1.17.1
    at Object.b (src/Pack.ts:224:9)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:20:1688) (src/components/PackCard.tsx:68:15)
    at Object.__ (src/components/PackCard.tsx:75:37)
    at Tt (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:1:10951) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at yn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

**Comment by misode** [comment]
The error is as expected. You can't downgrade a data pack

**Comment by TheeMrCheeky** [comment]
> The error is as expected. You can't downgrade a data pack

is it just impossible to downgrade one or can you make it so you can?? (new to datapacks started making them recently your stuff helps ALOT)

**Comment by misode** [comment]
Usually new versions add features which enable things that weren't possible before, so only a small subset of downgrade paths would be possible. Because the use case is so small I'm going going to spend the time developing those.
