### ISSUE TITLE
Error: Cannot parse "pack.mcmeta": Unexpected token ﻿ in JSON at position 0.

### ISSUE THREAD

**Issue by BenjaMenja** [misode/upgrader#3]
An error occurred while loading a data pack.
Not sure if i zipped the datapack incorrectly or something along those lines.
Data Pack:  [data.zip](https://github.com/misode/upgrader/files/6618259/data.zip)

```
Error: Cannot parse "pack.mcmeta": Unexpected token ﻿ in JSON at position 0.
    at a (https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:20396)
    at async Object.e.fromZip (https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:21314)
    at async https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:18416
    at async Promise.all (index 0)
    at async Object.onDrop [as dropfalse] (https://misode.github.io/upgrader/assets/index.eee13ca5.js:1:18370)
```

**Comment by misode** [comment]
🚀 A fix has been deployed. Thanks for reporting this issue!
