### ISSUE TITLE
TypeError: Error fixing configured feature minecraft:amethyst_geode: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by StereoMadnessss** [misode/upgrader#30]
An error occurred while upgrading a data pack.
Data Pack: <[Archive_21w44a](https://github.com/misode/upgrader/files/9421552/Archive_21w44a.zip)>

```
TypeError: Error fixing configured feature minecraft:amethyst_geode: Cannot read properties of undefined (reading 'startsWith')
    at qr (src/fixes/1.18.2/Feature.ts:50:43)
    at fixConfiguredFeature (src/fixes/1.18.2/Feature.ts:4:57)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1098) (src/Fix.ts:30:11)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:923) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:923) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1547) (src/Fix.ts:63:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:923) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1391) (src/Fix.ts:51:7)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:923) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1739) (src/Fix.ts:79:60)
```

**Comment by misode** [comment]
The fields `cannot_replace` and `invalid_blocks` are required, even in 21w44a, so I don't think the original pack would work in that version. However I still fixed the crash.
