### ISSUE TITLE
TypeError: Error fixing configured feature minecraft:new_ore/ore_iron: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by ArubikU** [misode/upgrader#31]
An error occurred while upgrading a data pack.
Data Pack: 
[Dark.zip](https://github.com/misode/upgrader/files/10087833/Dark.zip)

```
TypeError: Error fixing configured feature minecraft:new_ore/ore_iron: Cannot read properties of undefined (reading 'replace')
    at Ie (src/fixes/1.17/Feature.ts:16:24)
    at fixFeature (src/fixes/1.17/Feature.ts:5:62)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1098) (src/Fix.ts:30:11)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:929) (src/Fix.ts:13:10)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:929) (src/Fix.ts:13:10)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1547) (src/Fix.ts:63:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:923) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1391) (src/Fix.ts:51:7)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:923) (src/Fix.ts:12:21)
    at (https://misode.github.io/upgrader/assets/index.bc64b549.js:15:1739) (src/Fix.ts:79:60)
```

**Comment by misode** [comment]
The data pack you are trying to upgrade still has `name` instead of `type` in configured features. That format only existed for a few snapshots, that's why the upgrader didn't account for this.

Anyways it has been fixed now. Thanks for reporting!
