### ISSUE TITLE
Error: Invalid version range: 1.19.4 > 1.19

### ISSUE THREAD

**Issue by Thefatsparrow** [misode/upgrader#34]
An error occurred while upgrading a data pack.
Data Pack: 

```
Error: Invalid version range: 1.19.4 > 1.19
    at Object.b (src/Pack.ts:224:9)
    at upgrade (src/components/PackCard.tsx:68:15)
    at Object.__ (src/components/PackCard.tsx:76:3)
    at $t (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/index-f302cf4d.js:1:10475) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at kn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

if you could change the version of this datpack for me i would greatly appreciate that

**Comment by AstraUnknownDev** [comment]
Downgrading is not supported because in almost all cases it can never work.

**Comment by Thefatsparrow** [comment]
ahh alrighty thanks man!
