### ISSUE TITLE
TypeError: Error fixing noise settings minecraft:nether: Cannot read properties of undefined (reading 'xz_scale')

### ISSUE THREAD

**Issue by LeMako** [misode/upgrader#37]
An error occurred while upgrading a data pack.
Data Pack: 

```
TypeError: Error fixing noise settings minecraft:nether: Cannot read properties of undefined (reading 'xz_scale')
    at xz_scale (src/fixes/1.19/NoiseSettings.ts:96:34)
    at file (src/fixes/1.19/NoiseSettings.ts:48:23)
    at data (src/fixes/1.19/NoiseSettings.ts:83:22)
    at file (src/fixes/1.19/NoiseSettings.ts:48:23)
    at data (src/fixes/1.19/NoiseSettings.ts:88:22)
    at data (src/fixes/1.19/NoiseSettings.ts:82:22)
    at data (src/fixes/1.19/NoiseSettings.ts:83:22)
    at data (src/fixes/1.19/NoiseSettings.ts:82:22)
    at data (src/fixes/1.19/NoiseSettings.ts:82:22)
    at data (src/fixes/1.19/NoiseSettings.ts:83:22)
```

**Comment by misode** [comment]
@LeMako Could you attach your data pack that you were trying to upgrade? In versions before 1.19 the `noise.sampling` field in noise settings should always exist, but the error indicates that it didn't.
