### ISSUE TITLE
Error: The dropped files contain no zip files. Please zip the data pack first.

### ISSUE THREAD

**Issue by dodoisverycool** [misode/upgrader#40]
An error occurred while loading a data pack.
Data Pack: 

```
Error: The dropped files contain no zip files. Please zip the data pack first.
    at Object.o (src/App.tsx:71:23)
    at n (../../node_modules/preact/dist/preact.module.js:1:4351)
```

**Comment by spacepill0w** [comment]
> An error occurred while loading a data pack. Data Pack:
> 
> ```
> Error: The dropped files contain no zip files. Please zip the data pack first.
>     at Object.o (src/App.tsx:71:23)
>     at n (../../node_modules/preact/dist/preact.module.js:1:4351)
> ```

So did you zip the data pack? Was this an error putting the thing into the data pack updater, or when trying to load the data pack in minecraft?
