### ISSUE TITLE
Error: Found pack format 13, which does not match version 1.19.4

### ISSUE THREAD

**Issue by CodingPanda0623** [misode/upgrader#41]
1.19.4's pack format is 13

An error occurred while upgrading a data pack.
Data Pack: 

```
Error: Found pack format 13, which does not match version 1.19.4
    at Object.b (src/Pack.ts:218:10)
    at upgrade (src/components/PackCard.tsx:68:15)
    at Object.__ (src/components/PackCard.tsx:76:3)
    at $t (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/index-f302cf4d.js:1:10475) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at kn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

**Comment by misode** [comment]
Works as intended. 1.19.4's pack format is 12. The snapshot after it, 23w12a, has pack format 13.
