### ISSUE TITLE
Error: Found pack format 3, which does not match version 1.16.5

### ISSUE THREAD

**Issue by Dothuhaloi** [misode/upgrader#46]
An error occurred while upgrading a data pack.
Data Pack: 

```
Error: Found pack format 3, which does not match version 1.16.5
    at Object.b (src/Pack.ts:218:10)
    at upgrade (src/components/PackCard.tsx:68:15)
    at Object.__ (src/components/PackCard.tsx:76:3)
    at $t (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/index-f302cf4d.js:1:10475) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at kn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

**Comment by misode** [comment]
Data pack format 3 was never a valid pack format
