### ISSUE TITLE
Error: Found pack format 9, which does not match version 1.19

### ISSUE THREAD

**Issue by shloakvatsyayan** [misode/upgrader#48]
An error occurred while upgrading a data pack.
Data Pack: [New-Desert-Temple.zip](https://github.com/user-attachments/files/17270824/New-Desert-Temple.zip)

```
Error: Found pack format 9, which does not match version 1.19
    at Object.b (src/Pack.ts:218:10)
    at upgrade (src/components/PackCard.tsx:68:15)
    at Object.__ (src/components/PackCard.tsx:76:3)
    at $t (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at Array.forEach (<anonymous>)
    at (https://misode.github.io/upgrader/assets/index-f302cf4d.js:1:10475) (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at Array.forEach (<anonymous>)
    at kn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)
```

Pack format 9 is 1.19-1.19.2
![image](https://github.com/user-attachments/assets/ee9299c9-8f76-44cf-8cce-b773ae2cda0f)

**Comment by misode** [comment]
First problem: you're using the old (unmaintained) wiki. The wiki has moved to https://minecraft.wiki/

Second problem: you're looking at the resource pack format table. The data pack formats are different. Pack format 9 corresponds with 1.18.2

**Comment by shloakvatsyayan** [comment]
Alright thanks for the response and my bad!
