### ISSUE TITLE
Error: Error fixing advancements all_triggers:nether_travel: Cannot destructure property 'distance' of 'e.conditions' as it is undefined.

### ISSUE THREAD

**Issue by ManosSef** [misode/upgrader#9]
An error occurred while upgrading a data pack.
Data Pack: 
[datapack.zip](https://github.com/misode/upgrader/files/7620826/datapack.zip)

```
TypeError: Cannot destructure property 'distance' of 'e.conditions' as it is undefined.
    at xe (https://misode.github.io/upgrader/assets/index.53119e18.js:1:30572)
    at Array.forEach (<anonymous>)
    at https://misode.github.io/upgrader/assets/index.53119e18.js:1:30462
    at https://misode.github.io/upgrader/assets/index.53119e18.js:1:3332
    at async https://misode.github.io/upgrader/assets/index.53119e18.js:1:3190
    at async https://misode.github.io/upgrader/assets/index.53119e18.js:1:3190
    at async https://misode.github.io/upgrader/assets/index.53119e18.js:1:3816
    at async https://misode.github.io/upgrader/assets/index.53119e18.js:1:3190
    at async https://misode.github.io/upgrader/assets/index.53119e18.js:1:3670
    at async https://misode.github.io/upgrader/assets/index.53119e18.js:1:3190
```

**Comment by misode** [comment]
Thanks for the report, the fix is now live!
